version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres123
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres123
    ports:
      - 5432:5432